import React, { useState } from 'react';
import { Clock, CheckCircle, AlertTriangle, ChevronRight, Calendar, Check } from 'lucide-react';
import { PriorityBadge } from '../components/Common/Badge';
import { api } from '../api/client';

export function FollowupsView({ followups, leads, onSelectLead, onRefreshLeads }) {
    const [activeTab, setActiveTab] = useState('due');
    const [updatingId, setUpdatingId] = useState(null);

    const handleComplete = async (e, followupId) => {
        e.stopPropagation(); // prevent opening lead detail view
        setUpdatingId(followupId);
        try {
            await api.updateFollowup(followupId, 'completed', 'Marked completed from Follow-ups Console');
            if (onRefreshLeads) onRefreshLeads();
        } catch (err) {
            alert(`Failed to update follow-up: ${err.message}`);
        } finally {
            setUpdatingId(null);
        }
    };

    // Map followups with lead info
    const enrichedFollowups = followups.map((f) => {
        const lead = leads.find((l) => l.lead_id === f.lead_id);
        return {
            ...f,
            customer_name: lead?.customer_name || 'Unknown Customer',
            priority: lead?.priority || 'COLD',
            risk_status: lead?.risk_status || 'normal',
            lifecycle_status: lead?.lifecycle_status || 'analyzed',
        };
    });

    const dueFollowups = enrichedFollowups.filter((f) => f.status === 'scheduled' || f.status === 'overdue');
    const completedFollowups = enrichedFollowups.filter((f) => f.status === 'completed');
    const blockedFollowups = enrichedFollowups.filter((f) => f.lifecycle_status === 'opted_out' || f.lifecycle_status === 'resolved');

    const getDisplayedFollowups = () => {
        if (activeTab === 'due') return dueFollowups;
        if (activeTab === 'completed') return completedFollowups;
        if (activeTab === 'blocked') return blockedFollowups;
        return enrichedFollowups;
    };

    const displayedList = getDisplayedFollowups();

    return (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
            {/* Header */}
            <div>
                <h2 style={{ fontSize: '1.5rem', fontWeight: 700, marginBottom: '0.2rem' }}>Follow-up Operations Center</h2>
                <p style={{ fontSize: '0.875rem', color: 'var(--text-muted)' }}>
                    Automated and scheduled customer follow-up actions generated by Policy Engine.
                </p>
            </div>

            {/* Tabs Bar */}
            <div style={{ display: 'flex', gap: '0.5rem', borderBottom: '1px solid var(--border-color)', paddingBottom: '0.5rem' }}>
                <button
                    onClick={() => setActiveTab('due')}
                    className={`btn-secondary ${activeTab === 'due' ? 'active' : ''}`}
                    style={{
                        background: activeTab === 'due' ? 'var(--bg-dark-2)' : 'transparent',
                        borderColor: activeTab === 'due' ? 'var(--accent-primary)' : 'transparent',
                        fontWeight: activeTab === 'due' ? 600 : 500,
                    }}
                >
                    <Clock size={16} color="var(--color-warm)" /> Due / Active ({dueFollowups.length})
                </button>

                <button
                    onClick={() => setActiveTab('completed')}
                    className={`btn-secondary ${activeTab === 'completed' ? 'active' : ''}`}
                    style={{
                        background: activeTab === 'completed' ? 'var(--bg-dark-2)' : 'transparent',
                        borderColor: activeTab === 'completed' ? 'var(--accent-primary)' : 'transparent',
                        fontWeight: activeTab === 'completed' ? 600 : 500,
                    }}
                >
                    <CheckCircle size={16} color="var(--color-success)" /> Completed ({completedFollowups.length})
                </button>

                <button
                    onClick={() => setActiveTab('blocked')}
                    className={`btn-secondary ${activeTab === 'blocked' ? 'active' : ''}`}
                    style={{
                        background: activeTab === 'blocked' ? 'var(--bg-dark-2)' : 'transparent',
                        borderColor: activeTab === 'blocked' ? 'var(--accent-primary)' : 'transparent',
                        fontWeight: activeTab === 'blocked' ? 600 : 500,
                    }}
                >
                    <AlertTriangle size={16} color="var(--color-hot)" /> Blocked / Opted Out ({blockedFollowups.length})
                </button>
            </div>

            {/* Follow-up Cards List */}
            <div className="panel" style={{ padding: '1rem' }}>
                {displayedList.length === 0 ? (
                    <div style={{ padding: '3rem', textAlign: 'center', color: 'var(--text-dim)' }}>
                        No follow-ups currently found in this category.
                    </div>
                ) : (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '0.85rem' }}>
                        {displayedList.map((item) => (
                            <div
                                key={item.followup_id}
                                onClick={() => onSelectLead(item.lead_id)}
                                style={{
                                    padding: '1rem',
                                    borderRadius: 'var(--radius-sm)',
                                    background: 'var(--bg-dark-0)',
                                    border: '1px solid var(--border-color)',
                                    display: 'flex',
                                    alignItems: 'center',
                                    justifyContent: 'space-between',
                                    cursor: 'pointer',
                                    transition: 'border-color 0.15s ease',
                                }}
                                onMouseEnter={(e) => e.currentTarget.style.borderColor = 'var(--accent-primary)'}
                                onMouseLeave={(e) => e.currentTarget.style.borderColor = 'var(--border-color)'}
                            >
                                <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', flex: 1 }}>
                                    <div style={{
                                        width: '40px',
                                        height: '40px',
                                        borderRadius: 'var(--radius-sm)',
                                        background: 'var(--bg-dark-2)',
                                        display: 'flex',
                                        alignItems: 'center',
                                        justifyContent: 'center',
                                        color: 'var(--accent-primary)',
                                    }}>
                                        <Calendar size={20} />
                                    </div>

                                    <div>
                                        <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', marginBottom: '0.2rem' }}>
                                            <span style={{ fontWeight: 600, fontSize: '0.95rem' }}>{item.customer_name}</span>
                                            <PriorityBadge priority={item.priority} />
                                            <span className="badge-sub">{item.status.toUpperCase()}</span>
                                        </div>

                                        <p style={{ fontSize: '0.875rem', color: 'var(--text-main)', margin: 0, fontWeight: 500 }}>
                                            Action: {item.action}
                                        </p>
                                        {item.notes && (
                                            <span style={{ fontSize: '0.75rem', color: 'var(--text-dim)', display: 'block', marginTop: '0.1rem' }}>
                                                Notes: {item.notes}
                                            </span>
                                        )}
                                    </div>
                                </div>

                                <div style={{ display: 'flex', alignItems: 'center', gap: '1.25rem' }}>
                                    <div style={{ textAlign: 'right' }}>
                                        <span style={{ fontSize: '0.75rem', color: 'var(--text-dim)', display: 'block' }}>DUE TIMESTAMP</span>
                                        <span style={{ fontSize: '0.85rem', fontFamily: 'var(--font-mono)', color: 'var(--color-warm)' }}>
                                            {new Date(item.due_at).toLocaleString()}
                                        </span>
                                    </div>

                                    {item.status !== 'completed' && item.lifecycle_status !== 'opted_out' && (
                                        <button
                                            onClick={(e) => handleComplete(e, item.followup_id)}
                                            disabled={updatingId === item.followup_id}
                                            className="btn-secondary"
                                            style={{ padding: '0.4rem 0.65rem', fontSize: '0.8rem', color: 'var(--color-success)', borderColor: 'var(--border-success)' }}
                                        >
                                            <Check size={14} /> Complete
                                        </button>
                                    )}

                                    <ChevronRight size={18} color="var(--text-dim)" />
                                </div>
                            </div>
                        ))}
                    </div>
                )}
            </div>
        </div>
    );
}
